import { alpha } from '@mui/material/styles';

export const ui = {
  pageStack: { spacing: 3 },
  publicShell: {
    minHeight: '100vh',
    background:
      'radial-gradient(circle at top right, rgba(255, 218, 164, 0.35), transparent 24%), radial-gradient(circle at top left, rgba(122, 184, 154, 0.3), transparent 28%), linear-gradient(180deg, #f6fbf7 0%, #fffdfa 100%)',
  },
  siteHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    px: 4,
    py: 2.5,
    position: 'sticky',
    top: 0,
    zIndex: 10,
    backgroundColor: 'rgba(255, 253, 250, 0.86)',
    backdropFilter: 'blur(16px)',
    borderBottom: '1px solid rgba(20, 55, 44, 0.08)',
    flexDirection: { xs: 'column', md: 'row' },
  },
  siteBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
    color: 'text.primary',
  },
  siteBrandLogo: {
    width: 44,
    height: 44,
    objectFit: 'contain',
    borderRadius: 1.5,
    backgroundColor: '#fff',
    border: '1px solid rgba(20, 55, 44, 0.12)',
    p: 0.5,
  },
  siteBrandText: {
    fontWeight: 700,
    color: 'text.primary',
  },
  siteBrandLocation: {
    color: 'text.secondary',
    fontSize: '0.82rem',
  },
  siteNav: {
    alignItems: 'center',
  },
  siteMain: {
    maxWidth: 1180,
    mx: 'auto',
    p: { xs: 2.5, md: 3.5 },
  },
  siteLink: (theme, isActive = false) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    color: isActive ? theme.palette.primary.main : theme.palette.text.primary,
    fontWeight: 600,
    textDecoration: 'none',
  }),
  siteFooter: {
    mt: 4,
    px: 4,
    pt: 3.5,
    pb: 4,
    borderTop: '1px solid rgba(20, 55, 44, 0.08)',
    background:
      'linear-gradient(135deg, rgba(22, 51, 41, 0.96), rgba(35, 77, 61, 0.96)), rgba(18, 38, 32, 0.96)',
  },
  siteFooterInner: {
    width: '100%',
    color: '#f4f8f5',
  },
  siteFooterGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(4, minmax(0, 1fr))' },
    gap: 2.25,
  },
  siteFooterCard: { py: 0.5 },
  siteFooterHeading: { fontWeight: 700, color: '#f4f8f5' },
  siteFooterCopy: { color: 'rgba(244, 248, 245, 0.76)' },
  siteFooterNote: {
    mt: 3,
    pt: 2.5,
    borderTop: '1px solid rgba(244, 248, 245, 0.12)',
    color: 'rgba(244, 248, 245, 0.76)',
  },
  footerLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    color: 'rgba(244, 248, 245, 0.88)',
    textDecoration: 'none',
  },
  footerIconTop: { mt: '2px' },
  dashboardShell: {
    minHeight: '100vh',
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', lg: '280px minmax(0, 1fr)' },
    background:
      'radial-gradient(circle at top left, rgba(188, 228, 208, 0.55), transparent 28%), linear-gradient(180deg, #eef5f1 0%, #f8fbf9 100%)',
  },
  dashboardSidebar: {
    minHeight: { lg: '100vh' },
    p: 3,
    borderRight: '1px solid rgba(20, 55, 44, 0.08)',
    backgroundColor: 'rgba(250, 253, 251, 0.92)',
  },
  navStack: {
    overflowY: 'auto',
    pr: 0.5,
  },
  brandAvatar: {
    background: 'linear-gradient(135deg, #2f6b58, #7ab89a)',
  },
  sidebarBrand: { fontWeight: 700, color: 'text.primary' },
  sidebarSubtitle: { color: 'text.secondary' },
  navItem: (theme, isActive = false) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 14px',
    borderRadius: 14,
    color: theme.palette.text.primary,
    textDecoration: 'none',
    backgroundColor: isActive ? alpha(theme.palette.primary.main, 0.12) : 'transparent',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
  }),
  sidebarSpacer: { flex: 1 },
  sidebarSection: {
    fontSize: '0.82rem',
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    color: 'text.secondary',
  },
  userCard: {
    borderRadius: 2.25,
    border: '1px solid rgba(20, 55, 44, 0.08)',
    backgroundColor: '#f7fbf8',
    p: 2,
  },
  userName: { fontWeight: 700, color: 'text.primary' },
  userRole: { color: 'text.secondary' },
  userEmail: { color: 'text.secondary' },
  dashboardMain: { p: { xs: 2.5, lg: 3.5 } },
  heroPanel: {
    borderRadius: 3.5,
    border: '1px solid rgba(20, 55, 44, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    backdropFilter: 'blur(16px)',
    p: 3,
  },
  contentPanel: {
    borderRadius: 3.5,
    border: '1px solid rgba(20, 55, 44, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    backdropFilter: 'blur(16px)',
    p: 3,
  },
  publicHero: (compact = false) => ({
    p: compact ? 4.5 : 6,
    borderRadius: 4,
    border: '1px solid rgba(20, 55, 44, 0.08)',
    background:
      'linear-gradient(135deg, rgba(255, 250, 241, 0.96), rgba(236, 247, 241, 0.96)), rgba(255, 255, 255, 0.86)',
  }),
  publicHeroGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', lg: 'minmax(0, 1fr) 420px' },
    gap: 3,
    alignItems: 'center',
  },
  publicHeroImage: {
    width: '100%',
    minHeight: { xs: 240, md: 320 },
    maxHeight: 420,
    objectFit: 'cover',
    borderRadius: 3,
    border: '1px solid rgba(20, 55, 44, 0.1)',
    boxShadow: '0 22px 50px rgba(20, 55, 44, 0.14)',
  },
  eyebrow: {
    fontSize: '0.78rem',
    fontWeight: 700,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: 'primary.main',
  },
  publicTitle: {
    maxWidth: '11ch',
    m: 0,
    lineHeight: 0.98,
    color: 'text.primary',
  },
  heroTitle: {
    maxWidth: '16ch',
    fontWeight: 700,
    lineHeight: 1.02,
    color: 'text.primary',
  },
  loginTitle: {
    maxWidth: '14ch',
    fontWeight: 700,
    lineHeight: 1.02,
    color: 'text.primary',
  },
  publicCopy: { maxWidth: '62ch', color: 'text.secondary' },
  heroCopy: { color: 'text.secondary' },
  panelCopy: { color: 'text.secondary' },
  panelTitle: { fontWeight: 700, color: 'text.primary' },
  rowTitle: { fontWeight: 700, color: 'text.primary' },
  rowCopy: { color: 'text.secondary' },
  rowStrong: { fontWeight: 700, color: 'text.primary' },
  progressLabel: { fontWeight: 700, color: 'text.primary' },
  progressSubtext: { color: 'text.secondary' },
  statTitle: { fontWeight: 700, color: 'text.primary' },
  statValue: { color: 'text.primary', fontWeight: 700 },
  statNote: { color: 'text.secondary' },
  taskCard: {
    borderRadius: 2.25,
    border: '1px solid rgba(20, 55, 44, 0.08)',
    backgroundColor: '#f7fbf8',
    p: 2,
    display: 'flex',
    alignItems: { xs: 'flex-start', sm: 'center' },
    justifyContent: 'space-between',
    gap: 2,
    flexDirection: { xs: 'column', sm: 'row' },
  },
  recordCard: {
    borderRadius: 2.25,
    border: '1px solid rgba(20, 55, 44, 0.08)',
    backgroundColor: '#f7fbf8',
    p: 2,
    display: 'flex',
    alignItems: { xs: 'flex-start', sm: 'flex-start' },
    justifyContent: 'space-between',
    gap: 2,
    flexDirection: { xs: 'column', sm: 'row' },
  },
  propertyRow: {
    py: 2,
    display: 'flex',
    alignItems: { xs: 'flex-start', sm: 'center' },
    justifyContent: 'space-between',
    gap: 2,
    flexDirection: { xs: 'column', sm: 'row' },
  },
  rowMeta: { textAlign: { xs: 'left', sm: 'right' } },
  progressCard: {
    minWidth: 250,
    borderRadius: 2.25,
    border: '1px solid rgba(20, 55, 44, 0.08)',
    backgroundColor: '#f7fbf8',
    p: 2,
  },
  collectionProgress: {
    height: '10px !important',
    my: '14px',
    borderRadius: 999,
    backgroundColor: '#dcebe3 !important',
    '& .MuiLinearProgress-bar': {
      borderRadius: 999,
      background: 'linear-gradient(90deg, #2f6b58, #5aa27e)',
    },
  },
  statIcon: {
    display: 'inline-flex',
    p: 1.25,
    borderRadius: 1.75,
    color: '#1f4739',
    backgroundColor: '#e6f4ec',
  },
  statCard: {
    borderRadius: 3.5,
    border: '1px solid rgba(20, 55, 44, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    backdropFilter: 'blur(16px)',
    p: 2.5,
  },
  statsGrid: (columns) => ({
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      md: columns === 6 ? 'repeat(3, minmax(0, 1fr))' : columns === 4 ? 'repeat(2, minmax(0, 1fr))' : `repeat(${columns}, minmax(0, 1fr))`,
      xl: `repeat(${columns}, minmax(0, 1fr))`,
    },
    gap: 2.25,
  }),
  dashboardGrid: (overview = false) => ({
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', lg: overview ? '1.2fr 0.8fr' : '1.3fr 0.9fr' },
    gap: 2.25,
  }),
  platformChipGroup: { display: 'flex', flexWrap: 'wrap', gap: 1.25 },
  platformChipButton: { textTransform: 'none' },
  marketingPostGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))', xl: 'repeat(3, minmax(0, 1fr))' },
    gap: 2.25,
  },
  marketingPostCard: {
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  platformTagRow: { display: 'flex', flexWrap: 'wrap', gap: 1.25 },
  roomsGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))', xl: 'repeat(5, minmax(0, 1fr))' },
    gap: 2.25,
  },
  roomCard: {
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  roomCardMain: { display: 'grid', gap: 1.25 },
  roomCardMedia: {
    width: '100%',
    height: 160,
    borderRadius: 1.75,
    border: '1px solid rgba(20, 55, 44, 0.08)',
    overflow: 'hidden',
    background:
      'linear-gradient(135deg, rgba(233, 244, 237, 0.95), rgba(247, 251, 248, 0.98))',
    display: 'grid',
    placeItems: 'center',
  },
  roomCardImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    objectPosition: 'center',
    display: 'block',
  },
  roomFormPreview: {
    width: '100%',
    height: 140,
    objectFit: 'cover',
    borderRadius: 1.75,
    border: '1px solid rgba(20, 55, 44, 0.08)',
  },
};
